(("default" . ((user-emacs-directory . "~/.dotfiles/.emacs.d")))
 ("test" . ((user-emacs-directory . "~/.dotfiles/.config/emacs-profiles/test")
            (straight-p . t)))
 ("bare" . ((user-emacs-directory . "~/.dotfiles/.config/emacs-profiles/bare")
            (straight-p . t))))
