(defun pipa-ansi-terms ()
  "Launch *ansi-term* buffers for gform-frontend and gform and diplay both buffers."
  (interactive)
  (unless (match-buffers "^\\*ansi-term\\*$")
    (let ((default-directory "/Users/pepa/develop-hmrc/gform-frontend"))
      (ansi-term "/bin/zsh")
      (process-send-string (get-process "*ansi-term*") "ansi-gform-frontend\n")))
  (unless (match-buffers "^\\*ansi-term\\*<2>$")
    (let ((default-directory "/Users/pepa/develop-hmrc/gform"))
      (ansi-term "/bin/zsh")
      (process-send-string (get-process "*ansi-term*<2>") "ansi-gform\n")))
  (unless (one-window-p)
    (delete-window))
  (switch-to-buffer "*ansi-term*")
  (switch-to-buffer-other-window "*ansi-term*<2>"))
